#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#
# Generates parts/res/values*/strings.xml for TB520FUParts (Lenovo features).
# English is the default; strings equal to English are left out of the
# translations so they fall back to it.
import os, re

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'parts', 'res')

KEYS = [
 ('app_name', None), ('app_summary', None),
 ('charging_category', 'Charging'),
 ('charging_normal_title', None), ('charging_normal_summary', None),
 ('charging_limit_title', None), ('charging_limit_summary', None),
 ('charging_protect_title', None), ('charging_protect_summary', None),
 ('battery_category', 'Battery'),
 ('bypass_title', None), ('bypass_summary', None),
 ('standby_title', None), ('standby_summary', None),
 ('battery_maintenance_title', None), ('battery_maintenance_summary', None),
 ('battery_info_title', None), ('battery_info_summary', None),
 ('display_category', 'Display'),
 ('white_balance_title', None), ('white_balance_summary', None),
 ('white_balance_strength_title', None), ('white_balance_strength_summary', None),
 ('games_category', 'Games'),
 ('game_perf_title', None), ('game_perf_on', None), ('game_perf_off', None),
 ('game_perf_main_switch', None),
 ('game_mem_clean_title', None), ('game_mem_clean_summary', None),
 ('game_apps_category', None), ('game_app_add', None), ('game_app_remove', None),
 ('game_app_levels', None),
 ('game_cpu_category', None), ('game_gpu_category', None),
 ('game_perf_footer', None),
 ('pen_category', 'Pen'), ('pen_settings_title', None), ('pen_settings_summary', None),
 ('keyboard_category', 'Keyboard'),
 ('memory_category', 'Memory'), ('vram_title', None), ('vram_off', None), ('vram_size', None),
 ('vram_summary', None), ('vram_summary_pending', None),
 ('memory_status_title', None), ('memory_status_summary', None),
 ('memory_status_summary_off', None),
 ('reboot_title', None), ('reboot_message', None), ('reboot_now', None), ('reboot_later', None),
 ('play_store_category', 'Play Store'),
 ('spoof_title', None), ('spoof_summary', None), ('spoof_reboot_message', None),
]
ARRAYS = ['game_level_entries', 'game_cpu_level_summaries', 'game_gpu_level_summaries',
          'app_key_entries']

L = {}

L['en'] = dict(
 white_balance_strength_title='Strength', white_balance_strength_summary='How strongly the screen follows the ambient light. 100 % matches the stock Lenovo setting.',
 app_name='Lenovo features',
 app_summary='Battery, games, pen, keyboard, memory',
 charging_category='Charging',
 charging_normal_title='Normal', charging_normal_summary='Charges to 100%',
 charging_limit_title='Stop at 80%', charging_limit_summary='Charging stops at 80% and resumes below 76%',
 charging_protect_title='Battery protection',
 charging_protect_summary='Keeps the battery between 40% and 60% for a tablet that stays plugged in',
 battery_category='Battery',
 bypass_title='Bypass charging',
 bypass_summary='While plugged in, the tablet runs directly on charger power and the battery is not charged. Reduces heat while gaming. Charging resumes below 20%.',
 standby_title='Enhanced standby',
 standby_summary='Puts idle apps to sleep a few minutes after the screen turns off, so the battery lasts longer in standby',
 battery_maintenance_title='Battery health optimization',
 battery_maintenance_summary='Lowers the charging voltage step by step as the battery ages',
 battery_info_title='Battery status', battery_info_summary='Charge cycles %1$s · Health %2$s',
 display_category='Display',
 white_balance_title='Adaptive color tone',
 white_balance_summary='Adjusts the screen color temperature to the ambient light so it looks natural',
 games_category='Games',
 game_perf_title='Game performance', game_perf_on='On', game_perf_off='Off',
 game_perf_main_switch='Use per-app CPU and GPU settings',
 game_mem_clean_title='Free memory for games',
 game_mem_clean_summary='Closes background apps when an app from the list opens',
 game_apps_category='Apps', game_app_add='Add app', game_app_remove='Remove from list',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Settings apply only while the app is on screen. Clocks return to normal when you leave the app. Thermal protection always stays active.',
 pen_category='Pen', pen_settings_title='Lenovo pen',
 pen_settings_summary='Pen buttons, writing vibration, pairing',
 keyboard_category='Keyboard',
 memory_category='Memory', vram_title='Memory extension', vram_off='Off', vram_size='%1$d GB',
 vram_summary='%1$s. Uses storage as extra memory for apps kept in the background.',
 vram_summary_pending='%1$s after restart (now: %2$s)',
 memory_status_title='Current memory',
 memory_status_summary='RAM %1$s + %2$s (in use %3$s)',
 memory_status_summary_off='RAM %1$s (in use %2$s)',
 reboot_title='Restart required',
 reboot_message='The new memory extension size is used after the tablet restarts. Restart now?',
 reboot_now='Restart', reboot_later='Later',
 play_store_category='Play Store', spoof_title='Galaxy Tab S11 Ultra identity for Play Store', spoof_summary='Lets the Play Store offer apps it lists as incompatible with this tablet. Switching it may require clearing the Play Store data, and it applies only after a restart.', spoof_reboot_message='The Play Store identity change is applied after the tablet restarts. Restart now?',
 game_level_entries=['Power saving', 'Balanced', 'High performance'],
 game_cpu_level_summaries=['Lower clocks for less heat and longer play time',
                           'Keeps single core speed and caps the other cores to about 85 % for steady long sessions',
                           'No clock caps; thermal protection still applies'],
 game_gpu_level_summaries=['Lower graphics clock for less heat',
                           'Caps the graphics clock to about 85 % for less heat in long sessions',
                           'No graphics clock cap'],
 app_key_entries=['None', 'Screenshot', 'Notifications', 'Quick settings', 'Recent apps',
                  'Assistant', 'Search', 'Settings'],
)

L['ko'] = dict(
 white_balance_strength_title='강도', white_balance_strength_summary='주변 조명에 따라 화면 색을 바꾸는 정도입니다. 100%는 순정 Lenovo 설정과 같습니다.',
 app_name='Lenovo 기능',
 app_summary='배터리, 게임, 펜, 키보드, 메모리',
 charging_category='충전',
 charging_normal_title='일반', charging_normal_summary='100%까지 충전합니다',
 charging_limit_title='80%에서 충전 중지', charging_limit_summary='80%에서 충전을 멈추고 76% 아래로 내려가면 다시 충전합니다',
 charging_protect_title='배터리 보호',
 charging_protect_summary='항상 충전기에 연결해 두는 경우 배터리를 40~60%로 유지합니다',
 battery_category='배터리',
 bypass_title='우회 충전',
 bypass_summary='충전기 연결 중 배터리를 충전하지 않고 충전기 전원으로 바로 작동합니다. 게임 중 발열이 줄어듭니다. 20% 아래로 내려가면 다시 충전합니다.',
 standby_title='대기 절전 강화',
 standby_summary='화면이 꺼지고 몇 분 뒤 사용하지 않는 앱을 절전 상태로 전환해 대기 시간을 늘립니다',
 battery_maintenance_title='배터리 수명 최적화',
 battery_maintenance_summary='배터리 사용 기간에 따라 충전 전압을 단계적으로 낮춥니다',
 battery_info_title='배터리 상태', battery_info_summary='충전 횟수 %1$s · 성능 %2$s',
 display_category='디스플레이',
 white_balance_title='자연스러운 색감',
 white_balance_summary='주변 조명에 맞춰 화면 색온도를 자연스럽게 조절합니다',
 games_category='게임',
 game_perf_title='게임 성능 관리', game_perf_on='사용', game_perf_off='사용 안함',
 game_perf_main_switch='앱별 CPU·GPU 설정 사용',
 game_mem_clean_title='게임용 메모리 정리',
 game_mem_clean_summary='목록의 앱을 열 때 백그라운드 앱을 종료합니다',
 game_apps_category='앱', game_app_add='앱 추가', game_app_remove='목록에서 삭제',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='설정은 해당 앱이 화면에 있을 때만 적용됩니다. 앱에서 나가면 클럭이 원래대로 돌아옵니다. 발열 보호는 항상 동작합니다.',
 pen_category='펜', pen_settings_title='Lenovo 펜', pen_settings_summary='펜 버튼, 필기 진동, 연결',
 keyboard_category='키보드',
 memory_category='메모리', vram_title='메모리 확장', vram_off='사용 안함', vram_size='%1$d GB',
 vram_summary='%1$s. 백그라운드 앱을 위해 저장공간 일부를 메모리로 사용합니다.',
 vram_summary_pending='재시작 후 %1$s (현재: %2$s)',
 memory_status_title='현재 메모리',
 memory_status_summary='RAM %1$s + %2$s (사용 중 %3$s)',
 memory_status_summary_off='RAM %1$s (사용 중 %2$s)',
 reboot_title='재시작 필요',
 reboot_message='새 메모리 확장 크기는 태블릿을 다시 시작한 뒤 적용됩니다. 지금 다시 시작할까요?',
 reboot_now='다시 시작', reboot_later='나중에',
 play_store_category='Play 스토어', spoof_title='Play 스토어에 Galaxy Tab S11 Ultra로 표시', spoof_summary='이 태블릿과 호환되지 않는다고 표시되는 앱을 Play 스토어에서 설치할 수 있게 합니다. 전환하면 Play 스토어 데이터를 지워야 할 수 있고, 다시 시작한 뒤에만 적용됩니다.', spoof_reboot_message='Play 스토어 표시 변경은 태블릿을 다시 시작한 뒤 적용됩니다. 지금 다시 시작할까요?',
 game_level_entries=['절전', '균형', '고성능'],
 game_cpu_level_summaries=['클럭을 낮춰 발열을 줄이고 플레이 시간을 늘립니다',
                           '싱글 코어 속도는 유지하고 나머지 코어를 약 85%로 제한해 오래 플레이해도 안정적입니다',
                           '클럭 상한을 풀어 최대 성능을 냅니다 (발열 보호는 유지)'],
 game_gpu_level_summaries=['그래픽 클럭을 낮춰 발열을 줄입니다',
                           '그래픽 클럭을 약 85%로 제한해 오래 플레이할 때 발열을 줄입니다',
                           '그래픽 클럭 상한을 풉니다'],
 app_key_entries=['없음', '스크린샷', '알림', '빠른 설정', '최근 앱', '어시스턴트', '검색', '설정'],
)

L['ja'] = dict(
 white_balance_strength_title='強さ', white_balance_strength_summary='周囲の光に合わせて画面の色を変える度合いです。100%は標準のLenovo設定と同じです。',
 app_name='Lenovo 機能', app_summary='バッテリー、ゲーム、ペン、キーボード、メモリ',
 charging_category='充電',
 charging_normal_title='標準', charging_normal_summary='100%まで充電します',
 charging_limit_title='80%で充電を停止', charging_limit_summary='80%で充電を停止し、76%を下回ると再開します',
 charging_protect_title='バッテリー保護',
 charging_protect_summary='常に電源に接続して使う場合、バッテリーを40～60%に保ちます',
 battery_category='バッテリー',
 bypass_title='バイパス充電',
 bypass_summary='電源接続中はバッテリーを充電せず、充電器の電力で直接動作します。ゲーム中の発熱を抑えます。20%を下回ると充電を再開します。',
 standby_title='スタンバイ省電力の強化',
 standby_summary='画面オフの数分後に使っていないアプリをスリープさせ、待機時間を延ばします',
 battery_maintenance_title='バッテリー寿命の最適化',
 battery_maintenance_summary='バッテリーの劣化に合わせて充電電圧を段階的に下げます',
 battery_info_title='バッテリーの状態', battery_info_summary='充電回数 %1$s · 状態 %2$s',
 display_category='ディスプレイ',
 white_balance_title='自然な色合い',
 white_balance_summary='周囲の光に合わせて画面の色温度を自然に調整します',
 games_category='ゲーム',
 game_perf_title='ゲームパフォーマンス', game_perf_on='オン', game_perf_off='オフ',
 game_perf_main_switch='アプリ別のパフォーマンスプロファイルを使用',
 game_mem_clean_title='ゲーム用にメモリを解放',
 game_mem_clean_summary='リストのアプリを開くとバックグラウンドアプリを終了します',
 game_apps_category='アプリ', game_app_add='アプリを追加', game_app_remove='削除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='プロファイルはそのアプリが画面に表示されている間だけ適用されます。アプリを離れるとクロックは元に戻ります。熱保護は常に有効です。',
 pen_category='ペン', pen_settings_title='Lenovo ペン', pen_settings_summary='ペンボタン、書き心地の振動、ペアリング',
 keyboard_category='キーボード',
 memory_category='メモリ', vram_title='メモリ拡張', vram_off='オフ', vram_size='%1$d GB',
 vram_summary='%1$s。ストレージの一部をバックグラウンドアプリ用のメモリとして使います。',
 vram_summary_pending='再起動後 %1$s（現在: %2$s）',
 memory_status_title='現在のメモリ',
 memory_status_summary='RAM %1$s + %2$s（使用中 %3$s）',
 memory_status_summary_off='RAM %1$s（使用中 %2$s）',
 reboot_title='再起動が必要です',
 reboot_message='新しいメモリ拡張サイズはタブレットの再起動後に適用されます。今すぐ再起動しますか？',
 reboot_now='再起動', reboot_later='後で',
 play_store_category='Play ストア', spoof_title='Play ストアで Galaxy Tab S11 Ultra として表示', spoof_summary='このタブレットでは互換性がないと表示されるアプリを Play ストアからインストールできるようにします。切り替え後に Play ストアのデータを消去する必要がある場合があり、再起動後にのみ反映されます。', spoof_reboot_message='Play ストアの表示変更はタブレットの再起動後に反映されます。今すぐ再起動しますか？',
 game_level_entries=['省電力', 'バランス', '高パフォーマンス'],
 game_cpu_level_summaries=['クロックを下げて発熱を抑え、プレイ時間を延ばします',
                           '最大クロックを制限し、長時間でもフレームレートを安定させます',
                           '最大クロックと高めの最小クロックで素早く反応します'],
 game_gpu_level_summaries=['グラフィッククロックを下げて発熱を抑えます',
                           'グラフィッククロックを制限し、長時間でも安定させます',
                           '最大グラフィッククロックと高めの最小クロック'],
 app_key_entries=['なし', 'スクリーンショット', '通知', 'クイック設定', '最近のアプリ',
                  'アシスタント', '検索', '設定'],
)

L['zh-rCN'] = dict(
 white_balance_strength_title='强度', white_balance_strength_summary='屏幕随环境光改变颜色的程度。100% 与原厂 Lenovo 设置相同。',
 app_name='Lenovo 功能', app_summary='电池、游戏、手写笔、键盘、内存',
 charging_category='充电',
 charging_normal_title='标准', charging_normal_summary='充电至 100%',
 charging_limit_title='充至 80% 停止', charging_limit_summary='充至 80% 时停止，低于 76% 时恢复充电',
 charging_protect_title='电池保护',
 charging_protect_summary='长期插电使用时，将电量保持在 40%～60%',
 battery_category='电池',
 bypass_title='旁路充电',
 bypass_summary='插电时不给电池充电，由充电器直接为平板供电，减少游戏发热。电量低于 20% 时恢复充电。',
 standby_title='增强待机省电',
 standby_summary='屏幕关闭几分钟后让闲置应用进入休眠，延长待机时间',
 battery_maintenance_title='电池寿命优化',
 battery_maintenance_summary='随电池老化逐步降低充电电压',
 battery_info_title='电池状态', battery_info_summary='充电次数 %1$s · 健康度 %2$s',
 display_category='显示',
 white_balance_title='自然色调',
 white_balance_summary='根据环境光自动调节屏幕色温，使显示更自然',
 games_category='游戏',
 game_perf_title='游戏性能', game_perf_on='开启', game_perf_off='关闭',
 game_perf_main_switch='使用应用性能配置',
 game_mem_clean_title='游戏内存清理',
 game_mem_clean_summary='打开列表中的应用时关闭后台应用',
 game_apps_category='应用', game_app_add='添加应用', game_app_remove='移除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='配置仅在对应应用显示在屏幕上时生效，离开应用后频率恢复正常。温控保护始终有效。',
 pen_category='手写笔', pen_settings_title='Lenovo 手写笔', pen_settings_summary='笔按键、书写振动、配对',
 keyboard_category='键盘',
 memory_category='内存', vram_title='内存扩展', vram_off='关闭', vram_size='%1$d GB',
 vram_summary='%1$s。将部分存储空间用作后台应用的内存。',
 vram_summary_pending='重启后为 %1$s（当前：%2$s）',
 memory_status_title='当前内存',
 memory_status_summary='RAM %1$s + %2$s（已用 %3$s）',
 memory_status_summary_off='RAM %1$s（已用 %2$s）',
 reboot_title='需要重启', reboot_message='新的内存扩展大小将在平板重启后生效。立即重启？',
 reboot_now='重启', reboot_later='稍后',
 play_store_category='Play 商店', spoof_title='在 Play 商店中显示为 Galaxy Tab S11 Ultra', spoof_summary='让 Play 商店提供被标记为与本平板不兼容的应用。切换后可能需要清除 Play 商店数据，且仅在重启后生效。', spoof_reboot_message='Play 商店显示更改将在平板重启后生效。立即重启？',
 game_level_entries=['省电', '均衡', '高性能'],
 game_cpu_level_summaries=['降低频率，减少发热，延长游戏时间',
                           '限制最高频率，长时间游戏帧率更稳定',
                           '满频率并提高最低频率，响应更快'],
 game_gpu_level_summaries=['降低图形频率，减少发热',
                           '限制图形频率，长时间更稳定',
                           '图形满频率并提高最低频率'],
 app_key_entries=['无', '截屏', '通知', '快捷设置', '最近应用', '助理', '搜索', '设置'],
)

L['zh-rTW'] = dict(
 white_balance_strength_title='強度', white_balance_strength_summary='螢幕隨環境光改變色彩的程度。100% 與原廠 Lenovo 設定相同。',
 app_name='Lenovo 功能', app_summary='電池、遊戲、觸控筆、鍵盤、記憶體',
 charging_category='充電',
 charging_normal_title='標準', charging_normal_summary='充電至 100%',
 charging_limit_title='充至 80% 停止', charging_limit_summary='充至 80% 時停止，低於 76% 時恢復充電',
 charging_protect_title='電池保護',
 charging_protect_summary='長時間插電使用時，將電量維持在 40%～60%',
 battery_category='電池',
 bypass_title='旁路充電',
 bypass_summary='插電時不為電池充電，由充電器直接供電給平板，減少遊戲發熱。電量低於 20% 時恢復充電。',
 standby_title='強化待機省電',
 standby_summary='螢幕關閉幾分鐘後讓閒置應用程式進入休眠，延長待機時間',
 battery_maintenance_title='電池壽命最佳化',
 battery_maintenance_summary='隨電池老化逐步降低充電電壓',
 battery_info_title='電池狀態', battery_info_summary='充電次數 %1$s · 健康度 %2$s',
 display_category='顯示',
 white_balance_title='自然色調',
 white_balance_summary='依環境光自動調整螢幕色溫，讓顯示更自然',
 games_category='遊戲',
 game_perf_title='遊戲效能', game_perf_on='開啟', game_perf_off='關閉',
 game_perf_main_switch='使用應用程式效能設定檔',
 game_mem_clean_title='遊戲記憶體清理',
 game_mem_clean_summary='開啟清單中的應用程式時關閉背景應用程式',
 game_apps_category='應用程式', game_app_add='新增應用程式', game_app_remove='移除',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='設定檔僅在該應用程式顯示於螢幕上時生效，離開後時脈恢復正常。溫度保護始終有效。',
 pen_category='觸控筆', pen_settings_title='Lenovo 觸控筆', pen_settings_summary='筆按鍵、書寫震動、配對',
 keyboard_category='鍵盤',
 memory_category='記憶體', vram_title='記憶體擴充', vram_off='關閉', vram_size='%1$d GB',
 vram_summary='%1$s。將部分儲存空間作為背景應用程式的記憶體。',
 vram_summary_pending='重新啟動後為 %1$s（目前：%2$s）',
 memory_status_title='目前記憶體',
 memory_status_summary='RAM %1$s + %2$s（已用 %3$s）',
 memory_status_summary_off='RAM %1$s（已用 %2$s）',
 reboot_title='需要重新啟動', reboot_message='新的記憶體擴充大小會在平板重新啟動後生效。要立即重新啟動嗎？',
 reboot_now='重新啟動', reboot_later='稍後',
 play_store_category='Play 商店', spoof_title='在 Play 商店顯示為 Galaxy Tab S11 Ultra', spoof_summary='讓 Play 商店提供被標示為與本平板不相容的應用程式。切換後可能需要清除 Play 商店資料，且僅在重新啟動後生效。', spoof_reboot_message='Play 商店顯示變更會在平板重新啟動後生效。要立即重新啟動嗎？',
 game_level_entries=['省電', '平衡', '高效能'],
 game_cpu_level_summaries=['降低時脈，減少發熱，延長遊戲時間',
                           '限制最高時脈，長時間遊戲幀率更穩定',
                           '全速時脈並提高最低時脈，反應更快'],
 game_gpu_level_summaries=['降低圖形時脈，減少發熱',
                           '限制圖形時脈，長時間更穩定',
                           '圖形全速時脈並提高最低時脈'],
 app_key_entries=['無', '螢幕截圖', '通知', '快速設定', '最近使用的應用程式', '助理', '搜尋', '設定'],
)

L['de'] = dict(
 white_balance_strength_title='Stärke', white_balance_strength_summary='Wie stark sich der Bildschirm an das Umgebungslicht anpasst. 100 % entspricht der Lenovo-Werkseinstellung.',
 app_name='Lenovo-Funktionen', app_summary='Akku, Spiele, Stift, Tastatur, Speicher',
 charging_category='Laden',
 charging_normal_title='Normal', charging_normal_summary='Lädt bis 100 %',
 charging_limit_title='Bei 80 % stoppen', charging_limit_summary='Laden stoppt bei 80 % und wird unter 76 % fortgesetzt',
 charging_protect_title='Akkuschutz',
 charging_protect_summary='Hält den Akku zwischen 40 % und 60 %, wenn das Tablet dauerhaft angeschlossen ist',
 battery_category='Akku',
 bypass_title='Bypass-Laden',
 bypass_summary='Bei angeschlossenem Ladegerät läuft das Tablet direkt über das Netzteil, ohne den Akku zu laden. Weniger Wärme beim Spielen. Unter 20 % wird wieder geladen.',
 standby_title='Erweiterter Stand-by',
 standby_summary='Versetzt inaktive Apps wenige Minuten nach dem Ausschalten des Bildschirms in den Ruhezustand',
 battery_maintenance_title='Akkulebensdauer optimieren',
 battery_maintenance_summary='Senkt die Ladespannung schrittweise, wenn der Akku altert',
 battery_info_title='Akkustatus', battery_info_summary='Ladezyklen %1$s · Zustand %2$s',
 display_category='Display',
 white_balance_title='Adaptiver Farbton',
 white_balance_summary='Passt die Farbtemperatur des Bildschirms an das Umgebungslicht an',
 games_category='Spiele',
 game_perf_title='Spieleleistung', game_perf_on='An', game_perf_off='Aus',
 game_perf_main_switch='Leistungsprofile pro App verwenden',
 game_mem_clean_title='Speicher für Spiele freigeben',
 game_mem_clean_summary='Schließt Hintergrund-Apps, wenn eine App aus der Liste geöffnet wird',
 game_apps_category='Apps', game_app_add='App hinzufügen', game_app_remove='Entfernen',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Ein Profil gilt nur, solange seine App auf dem Bildschirm ist. Beim Verlassen der App kehren die Taktraten zum Normalwert zurück. Der Überhitzungsschutz bleibt immer aktiv.',
 pen_category='Stift', pen_settings_title='Lenovo-Stift', pen_settings_summary='Stifttasten, Schreibvibration, Kopplung',
 keyboard_category='Tastatur',
 memory_category='Speicher', vram_title='Speichererweiterung', vram_off='Aus', vram_size='%1$d GB',
 vram_summary='%1$s. Nutzt einen Teil des Speicherplatzes als Arbeitsspeicher für Hintergrund-Apps.',
 vram_summary_pending='%1$s nach Neustart (aktuell: %2$s)',
 memory_status_title='Aktueller Speicher',
 memory_status_summary='RAM %1$s + %2$s (belegt %3$s)',
 memory_status_summary_off='RAM %1$s (belegt %2$s)',
 reboot_title='Neustart erforderlich',
 reboot_message='Die neue Größe der Speichererweiterung gilt nach einem Neustart. Jetzt neu starten?',
 reboot_now='Neu starten', reboot_later='Später',
 play_store_category='Play Store', spoof_title='Galaxy Tab S11 Ultra im Play Store', spoof_summary='Lässt den Play Store Apps anbieten, die für dieses Tablet als nicht kompatibel gelistet sind. Nach dem Umschalten müssen eventuell die Play-Store-Daten gelöscht werden, und die Änderung gilt erst nach einem Neustart.', spoof_reboot_message='Die Änderung der Play-Store-Identität gilt nach einem Neustart des Tablets. Jetzt neu starten?',
 game_level_entries=['Energiesparen', 'Ausgewogen', 'Hohe Leistung'],
 game_cpu_level_summaries=['Niedrigere Taktraten für weniger Wärme und längere Spielzeit',
                           'Begrenzt Spitzentakt für stabile Bildraten bei langen Sitzungen',
                           'Voller Takt mit angehobenem Minimum für schnelle Reaktion'],
 game_gpu_level_summaries=['Niedrigerer Grafiktakt für weniger Wärme',
                           'Begrenzter Grafiktakt für lange, stabile Sitzungen',
                           'Voller Grafiktakt mit angehobenem Minimum'],
 app_key_entries=['Keine', 'Screenshot', 'Benachrichtigungen', 'Schnelleinstellungen',
                  'Letzte Apps', 'Assistant', 'Suche', 'Einstellungen'],
)

L['fr'] = dict(
 white_balance_strength_title='Intensité', white_balance_strength_summary='Degré d\'adaptation de l\'écran à la lumière ambiante. 100 % correspond au réglage Lenovo d\'origine.',
 app_name='Fonctions Lenovo', app_summary='Batterie, jeux, stylet, clavier, mémoire',
 charging_category='Charge',
 charging_normal_title='Normale', charging_normal_summary='Charge jusqu\'à 100 %',
 charging_limit_title='Arrêt à 80 %', charging_limit_summary='La charge s\'arrête à 80 % et reprend sous 76 %',
 charging_protect_title='Protection de la batterie',
 charging_protect_summary='Maintient la batterie entre 40 % et 60 % pour une tablette toujours branchée',
 battery_category='Batterie',
 bypass_title='Charge en dérivation',
 bypass_summary='Une fois branchée, la tablette fonctionne directement sur le chargeur sans charger la batterie. Moins de chaleur en jeu. La charge reprend sous 20 %.',
 standby_title='Veille renforcée',
 standby_summary='Met en veille les applications inactives quelques minutes après l\'extinction de l\'écran',
 battery_maintenance_title='Optimisation de la durée de vie',
 battery_maintenance_summary='Réduit progressivement la tension de charge à mesure que la batterie vieillit',
 battery_info_title='État de la batterie', battery_info_summary='Cycles de charge %1$s · Santé %2$s',
 display_category='Écran',
 white_balance_title='Teinte adaptative',
 white_balance_summary='Adapte la température de couleur de l\'écran à la lumière ambiante',
 games_category='Jeux',
 game_perf_title='Performances en jeu', game_perf_on='Activé', game_perf_off='Désactivé',
 game_perf_main_switch='Utiliser des profils de performances par application',
 game_mem_clean_title='Libérer la mémoire pour les jeux',
 game_mem_clean_summary='Ferme les applications en arrière-plan à l\'ouverture d\'une application de la liste',
 game_apps_category='Applications', game_app_add='Ajouter une application', game_app_remove='Retirer',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Un profil ne s\'applique que lorsque son application est à l\'écran. Les fréquences reviennent à la normale quand vous la quittez. La protection thermique reste toujours active.',
 pen_category='Stylet', pen_settings_title='Stylet Lenovo', pen_settings_summary='Boutons du stylet, vibration d\'écriture, association',
 keyboard_category='Clavier',
 memory_category='Mémoire', vram_title='Extension de mémoire', vram_off='Désactivée', vram_size='%1$d Go',
 vram_summary='%1$s. Utilise une partie du stockage comme mémoire pour les applications en arrière-plan.',
 vram_summary_pending='%1$s après redémarrage (actuellement : %2$s)',
 memory_status_title='Mémoire actuelle',
 memory_status_summary='RAM %1$s + %2$s (utilisée %3$s)',
 memory_status_summary_off='RAM %1$s (utilisée %2$s)',
 reboot_title='Redémarrage requis',
 reboot_message='La nouvelle taille d\'extension de mémoire s\'applique après le redémarrage de la tablette. Redémarrer maintenant ?',
 reboot_now='Redémarrer', reboot_later='Plus tard',
 play_store_category='Play Store', spoof_title='Afficher le Galaxy Tab S11 Ultra dans le Play Store', spoof_summary='Permet au Play Store de proposer des applications indiquées comme incompatibles avec cette tablette. Après la bascule, il peut être nécessaire d\'effacer les données du Play Store ; le changement ne s\'applique qu\'après un redémarrage.', spoof_reboot_message='Le changement d\'identité dans le Play Store s\'applique après le redémarrage de la tablette. Redémarrer maintenant ?',
 game_level_entries=['Économie d\'énergie', 'Équilibré', 'Hautes performances'],
 game_cpu_level_summaries=['Fréquences réduites pour moins de chaleur et plus d\'autonomie',
                           'Limite les pics de fréquence pour une fluidité stable sur la durée',
                           'Fréquences maximales avec un minimum relevé pour plus de réactivité'],
 game_gpu_level_summaries=['Fréquence graphique réduite pour moins de chaleur',
                           'Fréquence graphique limitée pour une stabilité durable',
                           'Fréquence graphique maximale avec un minimum relevé'],
 app_key_entries=['Aucune', 'Capture d\'écran', 'Notifications', 'Réglages rapides',
                  'Applications récentes', 'Assistant', 'Recherche', 'Paramètres'],
)

L['es'] = dict(
 white_balance_strength_title='Intensidad', white_balance_strength_summary='Cuánto se adapta la pantalla a la luz ambiental. 100 % coincide con el ajuste original de Lenovo.',
 app_name='Funciones de Lenovo', app_summary='Batería, juegos, lápiz, teclado, memoria',
 charging_category='Carga',
 charging_normal_title='Normal', charging_normal_summary='Carga hasta el 100 %',
 charging_limit_title='Detener al 80 %', charging_limit_summary='La carga se detiene al 80 % y se reanuda por debajo del 76 %',
 charging_protect_title='Protección de batería',
 charging_protect_summary='Mantiene la batería entre el 40 % y el 60 % en una tableta siempre enchufada',
 battery_category='Batería',
 bypass_title='Carga en bypass',
 bypass_summary='Con el cargador conectado, la tableta funciona directamente con la energía del cargador sin cargar la batería. Menos calor al jugar. La carga se reanuda por debajo del 20 %.',
 standby_title='Reposo mejorado',
 standby_summary='Suspende las aplicaciones inactivas unos minutos después de apagar la pantalla',
 battery_maintenance_title='Optimizar la vida útil de la batería',
 battery_maintenance_summary='Reduce gradualmente el voltaje de carga a medida que la batería envejece',
 battery_info_title='Estado de la batería', battery_info_summary='Ciclos de carga %1$s · Estado %2$s',
 display_category='Pantalla',
 white_balance_title='Tono de color adaptable',
 white_balance_summary='Ajusta la temperatura de color de la pantalla a la luz ambiental',
 games_category='Juegos',
 game_perf_title='Rendimiento en juegos', game_perf_on='Activado', game_perf_off='Desactivado',
 game_perf_main_switch='Usar perfiles de rendimiento por aplicación',
 game_mem_clean_title='Liberar memoria para juegos',
 game_mem_clean_summary='Cierra las aplicaciones en segundo plano al abrir una aplicación de la lista',
 game_apps_category='Aplicaciones', game_app_add='Añadir aplicación', game_app_remove='Quitar',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Un perfil solo se aplica mientras su aplicación está en pantalla. Las frecuencias vuelven a la normalidad al salir de la aplicación. La protección térmica siempre sigue activa.',
 pen_category='Lápiz', pen_settings_title='Lápiz Lenovo', pen_settings_summary='Botones del lápiz, vibración de escritura, vinculación',
 keyboard_category='Teclado',
 memory_category='Memoria', vram_title='Ampliación de memoria', vram_off='Desactivada', vram_size='%1$d GB',
 vram_summary='%1$s. Usa parte del almacenamiento como memoria para las aplicaciones en segundo plano.',
 vram_summary_pending='%1$s tras reiniciar (ahora: %2$s)',
 memory_status_title='Memoria actual',
 memory_status_summary='RAM %1$s + %2$s (en uso %3$s)',
 memory_status_summary_off='RAM %1$s (en uso %2$s)',
 reboot_title='Reinicio necesario',
 reboot_message='El nuevo tamaño de ampliación de memoria se aplica tras reiniciar la tableta. ¿Reiniciar ahora?',
 reboot_now='Reiniciar', reboot_later='Más tarde',
 play_store_category='Play Store', spoof_title='Mostrar Galaxy Tab S11 Ultra en Play Store', spoof_summary='Permite que Play Store ofrezca aplicaciones que marca como incompatibles con esta tablet. Tras cambiarlo puede que haya que borrar los datos de Play Store y solo se aplica después de reiniciar.', spoof_reboot_message='El cambio de identidad en Play Store se aplica después de reiniciar la tablet. ¿Reiniciar ahora?',
 game_level_entries=['Ahorro de energía', 'Equilibrado', 'Alto rendimiento'],
 game_cpu_level_summaries=['Frecuencias más bajas para menos calor y más tiempo de juego',
                           'Limita los picos de frecuencia para una tasa de fotogramas estable',
                           'Frecuencia máxima con un mínimo elevado para responder rápido'],
 game_gpu_level_summaries=['Frecuencia gráfica más baja para menos calor',
                           'Frecuencia gráfica limitada para sesiones largas estables',
                           'Frecuencia gráfica máxima con un mínimo elevado'],
 app_key_entries=['Ninguna', 'Captura de pantalla', 'Notificaciones', 'Ajustes rápidos',
                  'Aplicaciones recientes', 'Asistente', 'Buscar', 'Ajustes'],
)

L['it'] = dict(
 white_balance_strength_title='Intensità', white_balance_strength_summary='Quanto lo schermo si adatta alla luce ambientale. 100% corrisponde all\'impostazione Lenovo originale.',
 app_name='Funzioni Lenovo', app_summary='Batteria, giochi, penna, tastiera, memoria',
 charging_category='Ricarica',
 charging_normal_title='Normale', charging_normal_summary='Ricarica fino al 100%',
 charging_limit_title='Interrompi all\'80%', charging_limit_summary='La ricarica si ferma all\'80% e riprende sotto il 76%',
 charging_protect_title='Protezione batteria',
 charging_protect_summary='Mantiene la batteria tra il 40% e il 60% per un tablet sempre collegato',
 battery_category='Batteria',
 bypass_title='Ricarica bypass',
 bypass_summary='Quando è collegato, il tablet funziona direttamente con l\'alimentatore senza caricare la batteria. Meno calore durante il gioco. La ricarica riprende sotto il 20%.',
 standby_title='Standby avanzato',
 standby_summary='Sospende le app inattive pochi minuti dopo lo spegnimento dello schermo',
 battery_maintenance_title='Ottimizzazione durata batteria',
 battery_maintenance_summary='Riduce gradualmente la tensione di ricarica con l\'invecchiamento della batteria',
 battery_info_title='Stato batteria', battery_info_summary='Cicli di ricarica %1$s · Salute %2$s',
 display_category='Display',
 white_balance_title='Tonalità adattiva',
 white_balance_summary='Adatta la temperatura colore dello schermo alla luce ambientale',
 games_category='Giochi',
 game_perf_title='Prestazioni di gioco', game_perf_on='Attivo', game_perf_off='Disattivato',
 game_perf_main_switch='Usa profili di prestazioni per app',
 game_mem_clean_title='Libera memoria per i giochi',
 game_mem_clean_summary='Chiude le app in background quando si apre un\'app dell\'elenco',
 game_apps_category='App', game_app_add='Aggiungi app', game_app_remove='Rimuovi',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Un profilo si applica solo mentre la sua app è sullo schermo. Le frequenze tornano normali quando esci dall\'app. La protezione termica resta sempre attiva.',
 pen_category='Penna', pen_settings_title='Penna Lenovo', pen_settings_summary='Tasti della penna, vibrazione di scrittura, associazione',
 keyboard_category='Tastiera',
 memory_category='Memoria', vram_title='Estensione memoria', vram_off='Disattivata', vram_size='%1$d GB',
 vram_summary='%1$s. Usa parte dello spazio di archiviazione come memoria per le app in background.',
 vram_summary_pending='%1$s dopo il riavvio (ora: %2$s)',
 memory_status_title='Memoria attuale',
 memory_status_summary='RAM %1$s + %2$s (in uso %3$s)',
 memory_status_summary_off='RAM %1$s (in uso %2$s)',
 reboot_title='Riavvio necessario',
 reboot_message='La nuova dimensione dell\'estensione di memoria si applica dopo il riavvio del tablet. Riavviare ora?',
 reboot_now='Riavvia', reboot_later='Più tardi',
 play_store_category='Play Store', spoof_title='Mostra Galaxy Tab S11 Ultra nel Play Store', spoof_summary='Consente al Play Store di offrire app indicate come non compatibili con questo tablet. Dopo la modifica potrebbe servire cancellare i dati del Play Store; si applica solo dopo un riavvio.', spoof_reboot_message='La modifica dell\'identità nel Play Store si applica dopo il riavvio del tablet. Riavviare ora?',
 game_level_entries=['Risparmio energetico', 'Bilanciato', 'Prestazioni elevate'],
 game_cpu_level_summaries=['Frequenze più basse per meno calore e più tempo di gioco',
                           'Limita i picchi di frequenza per frame rate stabili nelle sessioni lunghe',
                           'Frequenza massima con minimo aumentato per una risposta rapida'],
 game_gpu_level_summaries=['Frequenza grafica più bassa per meno calore',
                           'Frequenza grafica limitata per sessioni lunghe stabili',
                           'Frequenza grafica massima con minimo aumentato'],
 app_key_entries=['Nessuna', 'Screenshot', 'Notifiche', 'Impostazioni rapide', 'App recenti',
                  'Assistente', 'Cerca', 'Impostazioni'],
)

L['pt-rBR'] = dict(
 white_balance_strength_title='Intensidade', white_balance_strength_summary='Quanto a tela se adapta à luz ambiente. 100% corresponde à configuração original da Lenovo.',
 app_name='Recursos Lenovo', app_summary='Bateria, jogos, caneta, teclado, memória',
 charging_category='Carregamento',
 charging_normal_title='Normal', charging_normal_summary='Carrega até 100%',
 charging_limit_title='Parar em 80%', charging_limit_summary='O carregamento para em 80% e volta abaixo de 76%',
 charging_protect_title='Proteção da bateria',
 charging_protect_summary='Mantém a bateria entre 40% e 60% em um tablet sempre conectado',
 battery_category='Bateria',
 bypass_title='Carregamento bypass',
 bypass_summary='Conectado ao carregador, o tablet funciona direto na energia do carregador sem carregar a bateria. Menos calor em jogos. O carregamento volta abaixo de 20%.',
 standby_title='Espera aprimorada',
 standby_summary='Coloca apps inativos para dormir alguns minutos após a tela desligar',
 battery_maintenance_title='Otimização da vida útil da bateria',
 battery_maintenance_summary='Reduz a tensão de carregamento aos poucos conforme a bateria envelhece',
 battery_info_title='Status da bateria', battery_info_summary='Ciclos de carga %1$s · Saúde %2$s',
 display_category='Tela',
 white_balance_title='Tom de cor adaptável',
 white_balance_summary='Ajusta a temperatura de cor da tela à luz ambiente',
 games_category='Jogos',
 game_perf_title='Desempenho em jogos', game_perf_on='Ativado', game_perf_off='Desativado',
 game_perf_main_switch='Usar perfis de desempenho por app',
 game_mem_clean_title='Liberar memória para jogos',
 game_mem_clean_summary='Fecha apps em segundo plano ao abrir um app da lista',
 game_apps_category='Apps', game_app_add='Adicionar app', game_app_remove='Remover',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Um perfil só se aplica enquanto o app está na tela. As frequências voltam ao normal quando você sai do app. A proteção térmica continua sempre ativa.',
 pen_category='Caneta', pen_settings_title='Caneta Lenovo', pen_settings_summary='Botões da caneta, vibração de escrita, pareamento',
 keyboard_category='Teclado',
 memory_category='Memória', vram_title='Extensão de memória', vram_off='Desativada', vram_size='%1$d GB',
 vram_summary='%1$s. Usa parte do armazenamento como memória para apps em segundo plano.',
 vram_summary_pending='%1$s após reiniciar (agora: %2$s)',
 memory_status_title='Memória atual',
 memory_status_summary='RAM %1$s + %2$s (em uso %3$s)',
 memory_status_summary_off='RAM %1$s (em uso %2$s)',
 reboot_title='Reinicialização necessária',
 reboot_message='O novo tamanho da extensão de memória é usado após reiniciar o tablet. Reiniciar agora?',
 reboot_now='Reiniciar', reboot_later='Mais tarde',
 play_store_category='Play Store', spoof_title='Exibir Galaxy Tab S11 Ultra na Play Store', spoof_summary='Permite que a Play Store ofereça apps que ela lista como incompatíveis com este tablet. Após a troca, pode ser preciso limpar os dados da Play Store; só vale depois de reiniciar.', spoof_reboot_message='A mudança de identidade na Play Store é aplicada após reiniciar o tablet. Reiniciar agora?',
 game_level_entries=['Economia de energia', 'Equilibrado', 'Alto desempenho'],
 game_cpu_level_summaries=['Frequências menores para menos calor e mais tempo de jogo',
                           'Limita picos de frequência para taxa de quadros estável',
                           'Frequência máxima com mínimo elevado para resposta rápida'],
 game_gpu_level_summaries=['Frequência gráfica menor para menos calor',
                           'Frequência gráfica limitada para sessões longas estáveis',
                           'Frequência gráfica máxima com mínimo elevado'],
 app_key_entries=['Nenhuma', 'Captura de tela', 'Notificações', 'Configurações rápidas',
                  'Apps recentes', 'Assistente', 'Pesquisar', 'Configurações'],
)

L['ru'] = dict(
 white_balance_strength_title='Интенсивность', white_balance_strength_summary='Насколько экран подстраивается под окружающее освещение. 100 % соответствует заводской настройке Lenovo.',
 app_name='Функции Lenovo', app_summary='Батарея, игры, стилус, клавиатура, память',
 charging_category='Зарядка',
 charging_normal_title='Обычная', charging_normal_summary='Заряжает до 100 %',
 charging_limit_title='Остановка на 80 %', charging_limit_summary='Зарядка останавливается на 80 % и возобновляется ниже 76 %',
 charging_protect_title='Защита батареи',
 charging_protect_summary='Держит заряд между 40 % и 60 %, если планшет постоянно подключен',
 battery_category='Батарея',
 bypass_title='Обходная зарядка',
 bypass_summary='При подключении планшет работает напрямую от зарядного устройства, не заряжая батарею. Меньше нагрев в играх. Зарядка возобновляется ниже 20 %.',
 standby_title='Улучшенный режим ожидания',
 standby_summary='Переводит неактивные приложения в сон через несколько минут после выключения экрана',
 battery_maintenance_title='Оптимизация срока службы батареи',
 battery_maintenance_summary='Постепенно снижает напряжение зарядки по мере износа батареи',
 battery_info_title='Состояние батареи', battery_info_summary='Циклы зарядки %1$s · Состояние %2$s',
 display_category='Экран',
 white_balance_title='Адаптивный цветовой тон',
 white_balance_summary='Подстраивает цветовую температуру экрана под окружающее освещение',
 games_category='Игры',
 game_perf_title='Производительность в играх', game_perf_on='Вкл.', game_perf_off='Выкл.',
 game_perf_main_switch='Профили производительности для приложений',
 game_mem_clean_title='Освобождать память для игр',
 game_mem_clean_summary='Закрывает фоновые приложения при запуске приложения из списка',
 game_apps_category='Приложения', game_app_add='Добавить приложение', game_app_remove='Удалить',
 game_app_levels='CPU %1$s · GPU %2$s',
 game_cpu_category='CPU', game_gpu_category='GPU',
 game_perf_footer='Профиль действует, только пока его приложение на экране. После выхода из приложения частоты возвращаются к норме. Защита от перегрева всегда активна.',
 pen_category='Стилус', pen_settings_title='Стилус Lenovo', pen_settings_summary='Кнопки стилуса, вибрация при письме, сопряжение',
 keyboard_category='Клавиатура',
 memory_category='Память', vram_title='Расширение памяти', vram_off='Выкл.', vram_size='%1$d ГБ',
 vram_summary='%1$s. Часть хранилища используется как память для фоновых приложений.',
 vram_summary_pending='%1$s после перезапуска (сейчас: %2$s)',
 memory_status_title='Текущая память',
 memory_status_summary='ОЗУ %1$s + %2$s (занято %3$s)',
 memory_status_summary_off='ОЗУ %1$s (занято %2$s)',
 reboot_title='Требуется перезапуск',
 reboot_message='Новый размер расширения памяти применится после перезапуска планшета. Перезапустить сейчас?',
 reboot_now='Перезапустить', reboot_later='Позже',
 play_store_category='Play Маркет', spoof_title='Galaxy Tab S11 Ultra в Play Маркете', spoof_summary='Позволяет Play Маркету предлагать приложения, помеченные как несовместимые с этим планшетом. После переключения может понадобиться очистить данные Play Маркета; применяется только после перезапуска.', spoof_reboot_message='Смена идентичности в Play Маркете применяется после перезапуска планшета. Перезапустить сейчас?',
 game_level_entries=['Энергосбережение', 'Баланс', 'Высокая производительность'],
 game_cpu_level_summaries=['Пониженные частоты: меньше нагрев, дольше игра',
                           'Ограничивает пиковые частоты для стабильного FPS в долгих сессиях',
                           'Полные частоты с повышенным минимумом для быстрого отклика'],
 game_gpu_level_summaries=['Пониженная частота графики: меньше нагрев',
                           'Ограниченная частота графики для долгой стабильной игры',
                           'Полная частота графики с повышенным минимумом'],
 app_key_entries=['Нет', 'Скриншот', 'Уведомления', 'Быстрые настройки', 'Недавние приложения',
                  'Ассистент', 'Поиск', 'Настройки'],
)


def esc(s):
    s = s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')
    if s.startswith('@') or s.startswith('?'):
        s = '\\' + s
    return s


def attrs(s):
    # a literal % without positional args would be taken as a format string
    literal = re.sub(r'%\d\$[sd]', '', s)
    return ' formatted="false"' if '%' in literal else ''


HEADER = '''<?xml version="1.0" encoding="utf-8"?>
<!--
     SPDX-FileCopyrightText: 2026 The LineageOS Project
     SPDX-License-Identifier: Apache-2.0
-->
<!-- Generated by tools/parts_strings.py; edit the table there. -->
<resources>
'''

en = L['en']
for lang, table in L.items():
    missing = [k for k, _ in KEYS if k not in table] + [a for a in ARRAYS if a not in table]
    assert not missing, (lang, missing)
    out = [HEADER]
    for key, _ in KEYS:
        v = table[key]
        if lang != 'en' and v == en[key] and key not in ('app_name',):
            continue
        out.append(f'    <string name="{key}"{attrs(v)}>{esc(v)}</string>\n')
    for a in ARRAYS:
        items = table[a]
        assert len(items) == len(en[a]), (lang, a)
        out.append(f'    <string-array name="{a}">\n')
        for it in items:
            assert it.count('%') <= 1, it  # arrays are not formatted
            out.append(f'        <item>{esc(it)}</item>\n')
        out.append('    </string-array>\n')
    out.append('</resources>\n')
    d = os.path.join(RES, 'values' if lang == 'en' else 'values-' + lang)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, 'strings.xml'), 'w') as f:
        f.write(''.join(out))
    print(lang, d)
